import test from 'node:test';import assert from 'node:assert/strict';import {readFile}from'node:fs/promises';import {JSDOM}from'jsdom';
for(const initialWidth of [1200,390])test('real renderer logic with mocked canvas: recenter, labels, arrow direction, pan, zoom, resize, disposal '+initialWidth,async()=>{
 const dom=new JSDOM('<canvas></canvas><div id="tip"></div>',{runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,c=w.document.querySelector('canvas');let width=initialWidth,labels=[],strokes=[],path=[];c.getBoundingClientRect=()=>({width,height:620,left:0,top:0});c.getContext=()=>({setTransform(){},clearRect(){labels=[];strokes=[];},setLineDash(){},beginPath(){path=[];},moveTo(x,y){path.push([x,y]);},lineTo(x,y){path.push([x,y]);},stroke(){strokes.push({path:[...path],width:this.lineWidth});},fill(){},fillRect(){},fillText(t,x,y){labels.push({t,x,y});}});
 for(const f of ['map-key','graph-view','network'])w.eval(await readFile(new URL('../src/'+f+'.js',import.meta.url),'utf8'));const a=w.PhysicsGraphView.connectedCore(JSON.parse(await readFile(new URL('../data/atlas.json',import.meta.url))));let picked,edgePicked;const map=w.PhysicsNetwork.mount(c,w.document.querySelector('#tip'),a,id=>{picked=id;map.select(id);},e=>edgePicked=e);
 assert.ok(labels.some(l=>l.t==='Force'));assert.ok(labels.some(l=>l.t==='Net force'));assert.ok(labels.some(l=>l.t==='Acceleration'));assert.ok(labels.some(l=>l.t==='causes'));let snap=map.snapshot();assert.ok(snap.nodes.length<=6);const from=snap.nodes.find(n=>n.id==='net_force'),to=snap.nodes.find(n=>n.id==='acceleration');const line=strokes.find(s=>s.width===3&&s.path.length===2);assert.ok(line);assert.ok(Math.hypot(line.path[0][0]-from.x,line.path[0][1]-from.y)<110);assert.ok(Math.hypot(line.path[1][0]-to.x,line.path[1][1]-to.y)<110);
 const click=p=>{for(const type of ['pointerdown','pointerup'])c.dispatchEvent(new w.MouseEvent(type,{clientX:p.x,clientY:p.y}));};click(snap.labels.find(l=>l.edge.relation==='causes'));assert.equal(edgePicked.kind,'causation');click(to);assert.equal(picked,'acceleration');
 map.select('ion');snap=map.snapshot();assert.equal(snap.selected,'ion');assert.ok(labels.some(l=>l.t==='Ion'));assert.ok(!snap.nodes.some(n=>n.id==='net_force'));assert.ok(snap.edges.every(e=>a.edges.some(x=>x.id===e.id)));
 const before=JSON.stringify(snap.nodes);map.zoom(1.3);assert.notEqual(JSON.stringify(map.snapshot().nodes),before);for(const [type,x,y]of [['pointerdown',10,10],['pointermove',50,70],['pointerup',50,70]])c.dispatchEvent(new w.MouseEvent(type,{clientX:x,clientY:y}));assert.notEqual(JSON.stringify(map.snapshot().nodes),before);width+=50;w.dispatchEvent(new w.Event('resize'));assert.ok(map.snapshot().nodes.every(n=>Number.isFinite(n.x)&&Number.isFinite(n.y)));map.next();assert.equal(map.counts().offset,0);map.next();assert.ok(map.counts().offset>0);map.fit();map.destroy();dom.window.close();
});
