import test from 'node:test';import assert from 'node:assert/strict';import {readFile}from'node:fs/promises';import {JSDOM,VirtualConsole}from'jsdom';
test('application integration in JSDOM: default mechanics, search navigation, edge evidence, source archives, routes',async()=>{
 const html=await readFile(new URL('../index.html',import.meta.url),'utf8');const atlas=JSON.parse(await readFile(new URL('../data/atlas.json',import.meta.url)));const failures=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>failures.push(e));const dom=new JSDOM(html,{url:'http://localhost:4173/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window,d=w.document;let labels=[];w.fetch=async()=>({ok:true,json:async()=>atlas});w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLCanvasElement.prototype.getContext=()=>({setTransform(){},clearRect(){labels=[];},setLineDash(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},fill(){},fillRect(){},fillText(t){labels.push(t);}});
 for(const f of ['map-key','graph-view','network','app'])w.eval(await readFile(new URL('../src/'+f+'.js',import.meta.url),'utf8'));await new Promise(r=>setTimeout(r,100));assert.notEqual(d.querySelector('#map-mode').textContent,'ATLAS UNAVAILABLE',d.querySelector('#inspector').textContent.slice(0,500));assert.equal(d.querySelector('#inspector h3').textContent,'Force');for(const t of ['Force','Net force','Acceleration','causes'])assert.ok(labels.includes(t),t);assert.match(d.querySelector('#lens-controls').textContent,/nonzero net force/);assert.ok(d.querySelectorAll('[data-lens-node]').length<=6);
 const cause=[...d.querySelectorAll('[data-lens-edge]')].find(b=>b.textContent.includes('Net force → causes → Acceleration'));assert.ok(cause);cause.click();assert.match(d.querySelector('#edge-evidence').textContent,/constant positive mass/);assert.match(d.querySelector('#edge-evidence').textContent,/OpenStax/);
 const search=d.querySelector('#search');for(const id of ['entropy','ion','quantum_mechanics','special_relativity']){search.value=id;search.dispatchEvent(new w.Event('input'));const button=d.querySelector('#search-results [data-concept="'+id+'"]');assert.ok(button,id);button.click();assert.match(d.querySelector('#map-mode').textContent,/FOCUS/);assert.ok(new URL(w.location.href).searchParams.get('concept')===id);assert.ok(d.querySelectorAll('[data-lens-edge]').length>0);assert.ok(labels.includes(atlas.nodes.find(n=>n.id===id).label));}
 assert.ok(d.querySelector('#inspector .related-material'));const raw=d.querySelector('.raw-record');raw.open=true;raw.dispatchEvent(new w.Event('toggle'));assert.match(raw.textContent,/aliases/);assert.match(raw.textContent,/supporting/);d.querySelector('#more-neighbors').click();assert.ok(d.querySelectorAll('[data-lens-node]').length>1);d.querySelector('#reset-map').click();assert.equal(d.querySelector('#inspector h3').textContent,'Force');d.querySelector('#route-list button').click();assert.equal(d.querySelector('#route-detail').hidden,false);d.querySelector('#route-next').click();assert.match(d.querySelector('#route-detail').textContent,/02/);const core=w.PhysicsGraphView.connectedCore(atlas);
 assert.equal(d.querySelector('#metric-concepts').textContent,core.nodes.length.toLocaleString());
 assert.equal(d.querySelectorAll('#domain-key .domain-item').length,13);
 assert.equal(d.querySelectorAll('#relation-key .relation-key-item').length,8);
 assert.equal(d.querySelectorAll('#source-links a[download]').length,atlas.documents.length+1);
 search.value='concept_force';search.dispatchEvent(new w.Event('input'));
 assert.equal(d.querySelector('#search-results [data-concept]').dataset.concept,'force');
 search.value='net ionic charge';search.dispatchEvent(new w.Event('input'));
 d.querySelector('#search-results [data-concept="ion"]').click();
 assert.equal(d.querySelector('#edge-evidence').hidden,true);
 assert.ok(d.querySelector('#inspector').textContent.includes('Q/e = N_protons - N_electrons'));
 assert.match(d.querySelector('#inspector').textContent,/L67-L70/);
 assert.equal(d.querySelectorAll('#inspector .relation-entry').length,core.edges.filter(e=>e.source==='ion'||e.target==='ion').length);
 const context=d.querySelector('.document-context');context.open=true;context.dispatchEvent(new w.Event('toggle'));
 assert.match(context.querySelector('pre').textContent,/schema_version/);
 const catalog=d.querySelector('#catalog-search');catalog.value='concept_special_relativity';catalog.dispatchEvent(new w.Event('input'));
 d.querySelector('#catalog-items [data-concept="special_relativity"]').click();
 assert.match(d.querySelector('#inspector .related-material').textContent,/Learning Paths/);
 const source=atlas.documents.find(doc=>doc.file.startsWith('ion_full'));
 d.querySelector('[data-topic="'+source.graphId+'"]').click();
 assert.equal(d.querySelector('[data-topic="'+source.graphId+'"]').getAttribute('aria-pressed'),'true');
 catalog.value='';catalog.dispatchEvent(new w.Event('input'));
 for(const button of d.querySelectorAll('#catalog-items [data-concept]')) assert.ok(core.nodes.find(n=>n.id===button.dataset.concept).topics.includes(source.graphId));
 d.querySelector('[data-topic="all"]').click();
 d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
 assert.equal(d.querySelector('#inspector h3').textContent,'Force');
 assert.equal(new URL(w.location.href).searchParams.has('concept'),false);
 assert.equal(d.querySelector('#search-results').hidden,true);
 d.querySelector('#search').blur();d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'/',bubbles:true}));
 assert.equal(d.activeElement,d.querySelector('#search'));
 assert.deepEqual(failures,[]);w.dispatchEvent(new w.Event('pagehide'));dom.window.close();
});
